name: restrr
description: Dart package which allows to communicate with the financrr REST API.
version: 0.12.0
repository: https://github.com/financrr/restrr

environment:
  sdk: ^3.4.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.5
dependencies:
  dio: ^5.4.3+1
  logging: ^1.3.0
