name: restrr
description: Dart package which allows to communicate with the financrr REST API.
version: 0.11.0
repository: https://github.com/financrr/restrr

environment:
  sdk: ^3.2.4

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.0
dependencies:
  dio: ^5.4.0
  logging: ^1.2.0
